import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import {
  isArchivedModelUnconfirmed,
  isArchivedStyleMismatch,
} from '../server/vercel-routes/cw/archive.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
dotenv.config({ path: path.join(root, '.env.local'), quiet: true });
const directory = process.env.CW_ARCHIVE_DIR;
if (!directory) throw new Error('CW_ARCHIVE_DIR is required');
const readJson = async (relative: string) =>
  JSON.parse(await fs.readFile(path.join(directory, relative), 'utf8'));
const runtime = await readJson('runtime-index.json');
const configs = new Map(runtime.configs.map((config: any) => [config.id, config]));
const tuples = await readJson('measurement-tuples.json');
const assets = new Set<string>();
for (const tuple of tuples) {
  if (isArchivedModelUnconfirmed(configs.get(tuple.productId), tuple.reference)) continue;
  const record = await readJson(`measurements/${tuple.file}`);
  if (
    record.httpStatus !== 200 ||
    Number(record.data?.status) !== 200 ||
    isArchivedStyleMismatch(tuple.style, tuple.styleCode, record.data?.content)
  )
    continue;
  let map: any[];
  try {
    map = await readJson(`asset-maps/${tuple.file}`);
  } catch {
    continue;
  }
  for (const asset of map) {
    const name = String(asset.localPath || '').replace(/^assets\//, '');
    if (!asset.error && /^[a-f0-9]{64}\.[a-zA-Z0-9]{1,10}$/.test(name)) assets.add(name);
  }
}
// This server-only list prevents direct image requests from exposing unconfirmed
// or mismatched-style diagrams, even when a caller knows their archived hash.
const source = `// Generated by scripts/cw-archive-asset-access.ts from confirmed measurement records.\n// Contains file identifiers only. Regenerate when the archive snapshot changes.\nconst confirmedAssets = new Set<string>(${JSON.stringify([...assets].sort(), null, 2)});\n\nexport function isConfirmedArchiveAsset(name: string): boolean {\n  return confirmedAssets.has(name);\n}\n`;
await fs.writeFile(path.join(root, 'server/vercel-routes/cw/asset-access.ts'), source);
console.log(JSON.stringify({ confirmedAssets: assets.size, serverOnly: true }));
