/** Generate server-only lookup metadata; never include measurement values or diagrams. */
import fs from 'node:fs/promises';
import path from 'node:path';
import dotenv from 'dotenv';
import {
  isArchivedModelUnconfirmed,
  isArchivedStyleMismatch,
} from '../server/vercel-routes/cw/archive.ts';
dotenv.config({ path: '.env.local', quiet: true });
const directory = process.env.CW_ARCHIVE_DIR;
if (!directory) throw new Error('CW_ARCHIVE_DIR is required');
const read = async (file: string) =>
  JSON.parse(await fs.readFile(path.join(directory, file), 'utf8'));
const runtime = await read('runtime-index.json');
const tuples = await read('measurement-tuples.json');
const configs = new Map<string, any>(runtime.configs.map((c: any) => [c.id, c]));
const statuses = new Map<string, string>();
const key = (reference: string, styleCode: string) => `${reference}|${styleCode}`.toUpperCase();
for (const tuple of tuples) {
  const config = configs.get(tuple.productId);
  let status = 'unavailable';
  if (isArchivedModelUnconfirmed(config, tuple.reference)) status = 'unconfirmed';
  else {
    const record = await read(`measurements/${tuple.file}`);
    if (record.httpStatus === 200 && Number(record.data?.status) === 200)
      status = isArchivedStyleMismatch(tuple.style, tuple.styleCode, record.data?.content)
        ? 'review'
        : 'confirmed';
  }
  statuses.set(key(tuple.reference, tuple.styleCode), status);
}
const products = runtime.products.map((product: any) => {
  const config = configs.get(product.id);
  const versions = config?.versionOptions?.length
    ? config.versionOptions
    : [{ code: '', label: '', scopedReference: product.reference }];
  const styles = config?.styleOptions || [];
  const selections = versions.flatMap((version: any) =>
    styles.map((style: any) => {
      const reference = version.scopedReference || product.reference;
      return {
        key: `${product.id}|${reference}|${style.styleCode}`,
        productId: product.id,
        productReference: product.reference,
        scopedReference: reference,
        versionCode: version.code,
        versionLabel: version.label,
        style: style.style,
        styleCode: style.styleCode,
        status: isArchivedModelUnconfirmed(config, reference)
          ? 'unconfirmed'
          : statuses.get(key(reference, style.styleCode)) || 'unavailable',
      };
    })
  );
  return {
    id: product.id,
    reference: product.reference,
    name:
      product.translations?.edges?.find((e: any) => e.node?.lang === 'en')?.node?.name ||
      product.name ||
      product.reference,
    brand: product.brand?.name || '',
    status: product.status,
    aliases: [
      ...new Set(
        [
          ...(product.catalogueTitles || []),
          ...(product.translations?.edges || []).map((e: any) => e.node?.name),
        ].filter(Boolean)
      ),
    ],
    selections,
  };
});
const source = `// Generated by scripts/cw-search-catalogue.ts. Server only; protected by Sofapaint authentication.\n// Product metadata and confirmation/readiness only. No measurement values or asset URLs.\nexport const measurementCatalogue: { snapshot: string; products: any[] } = JSON.parse(${JSON.stringify(JSON.stringify({ snapshot: '2026-09-29', products }))});\n`;
await fs.writeFile('server/vercel-routes/cw/search-catalogue.ts', source);
console.log(
  JSON.stringify({
    products: products.length,
    selections: products.reduce((n: number, p: any) => n + p.selections.length, 0),
    bytes: source.length,
  })
);
